version: "3"
services:
  db:
    image: mysql:8.0
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'auzzythebearshop'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'auzzy'
      # You can use whatever password you like
      MYSQL_PASSWORD: '123456'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123456'
    expose:
      # Opens port 3306 on the container
      - '3306'

  backend:
    image: auzzythebear
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: 'auzzythebearshop'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'auzzy'
      # You can use whatever password you like
      MYSQL_PASSWORD: '123456'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123456'
      DATABASE_ADDRESS: 'my_mysql'
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
