INSERT INTO products (productid, description, imageurl, name, price) VALUES
(1,
'Classic Matcha Latte bring a unique and fresh taste for your day',
'http://localhost:8080/images/upload-dir/M1.CLASSICMATCHALATTE.avif',
'Classic Matcha Latte',
 9),
(2,
'Experience a unique and refreshing twist on a classic latte with our strawberry matcha latte! afternoon treat. Matcha is known for its antioxidant and energy-boosting properties, while the strawberries add a natural sweetness and a burst of vitamins. The creamy milk creates a smooth texture that perfectly complements the earthy flavor of the matcha and the sweet strawberries. Our strawberry matcha latte is a perfect choice for those looking for a unique and refreshing latte experience.',
'http://localhost:8080/images/upload-dir/M2. STRAWBERRY MATCHA LATTE .avif',
'Strawberry Matcha Latte',
8),
(3,
'Experience a unique and refreshing twist on a classic latte with our mango matcha latte! Made with high-quality matcha powder, combined with fresh and juicy homemade mango puree, this latte is a delicious and healthy way to start your day or enjoy as an afternoon treat. Matcha is known for its antioxidant and energy-boosting properties, while the mangoes add a natural sweetness and a burst of vitamins. The creamy milk creates a smooth texture that perfectly complements the earthy flavor of the matcha and the sweet mangoes. Our mango matcha latte is a perfect choice for those looking for a unique and refreshing latte experience.',
'http://localhost:8080/images/upload-dir/M3. MANGO MATCHA LATTE .avif',
'Mango Matcha Latte',
7),
(4,
'*Strawberry Smoothie* Made with fresh, ripe strawberries and blended to perfection with creamy half & half, our strawberry smoothie is a healthy treat that is packed with vitamins and antioxidants, making it the perfect way to start your day or refuel after a workout Contains Dairy (Non-dairy alternatives are available in the options)',
'http://localhost:8080/images/upload-dir/SM1. PINK DELIGHT .avif',
'Pink Delight',
11),
(5,
'*Mango Smoothie* Savor the sweet, tropical taste of our mango smoothie! We start with perfectly ripe, juicy mangoes and blend them with creamy half & half until we get the velvety texture. Bursting with flavor and essential vitamins, this refreshing smoothie is a perfect healthy breakfast on the go or refuel after a workout. Contains Dairy (Non-dairy alternatives are available in the options)',
'http://localhost:8080/images/upload-dir/SM2. MANGO TANGO .avif',
'Mango Tango',
12),
(6,
'Indulge in the creamy and nutritious goodness of our avocado smoothie! Made with fresh and ripe avocados, blended with creamy half & half, our avocado smoothie is a healthy and delicious option for any time of day. Avocados are packed with essential vitamins and healthy fats, making this smoothie a perfect choice for a post-workout recovery drink or a nutritious breakfast. Contains Dairy',
'http://localhost:8080/images/upload-dir/SM7. AVOCADO SMOOTHIE .avif',
'Avocado Smoothie',
10),
(7,
'A Caramel Frappuccino is made by blending espresso with caramel syrup, milk, and ice until it becomes a chunky, blended drink. A swirl of whipped cream on top gives it a decadent finish, then you must add a drizzle of caramel sauce.',
'http://localhost:8080/images/upload-dir/F1. CARAMEL FRAPPUCCINO .avif',
'Caramel Frappuccino',
7),
(8,
'A mix of cookies, milk and ice are blended to make a perfect icy creamy cookie texture then finished with a delicious Cookies & Cream topping.',
'http://localhost:8080/images/upload-dir/F2. COOKIE & CREAM FRAPPUCCINO .avif',
'Cookie & Cream Frappuccino',
6),
(9,
'This rich and creamy blend of vanilla bean, milk and ice topped with whipped cream takes va-va-vanilla flavor to another level. ',
'http://localhost:8080/images/upload-dir/F3. VANILLA FRAPPUCINO .avif',
'Vanilla Frappuccino',
5),
(10,
'This rich and creamy blend of vanilla bean, milk and ice topped with whipped cream takes va-va-vanilla flavor to another level. ',
'http://localhost:8080/images/upload-dir/F5. MOCHA FRAPPUCCINO .avif',
'Mocha Frappuccino',
5),
(11,
'Mango, banana smoothie (non-dairy alternatives are available in the options) the perfect balance of sweet and tangy',
'http://localhost:8080/images/upload-dir/SM4. YELLOW YATCH .avif',
'Yellow Yatch',
7),
(12,
'Avocado, banana & spinach smoothie (contains dairy).',
'http://localhost:8080/images/upload-dir/SM8. LOS GATOS GREENS .avif',
'Los Gatos Greens',
8),
(13,
'Strawberry Banana Smoothie (Non-dairy alternatives are available in the options) The ultimate flavor combination of sweet strawberries and creamy bananas with our Strawberry Banana Twist smoothie',
'http://localhost:8080/images/upload-dir/SM3. STRAWBERRY BANANA TWIST .avif',
'Strawberry Banana Twist',
8);
